# Generated by Django 4.2.7 on 2024-02-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Аватар'),
        ),
    ]
