# Generated by Django 4.2.7 on 2024-02-10 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('image', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Фотография')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Заголовок')),
                ('description', models.TextField(max_length=3000, verbose_name='Контент')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('status', models.CharField(choices=[('moderation', 'На модерацию'), ('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('pending_deletion', 'На удаление')], default='moderation', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('text', models.TextField(max_length=400, verbose_name='Комментарий')),
                ('announcements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.announcements', verbose_name='Обьявление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='announcements',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='webapp.category', verbose_name='Категория'),
        ),
    ]
